name: quizz
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Ajout des assets ici
  assets:
    - assets/quiz1.png
    - assets/Q1.png
    - assets/Q2.png
    - assets/Q3.png
    - assets/Q4.png
    - assets/Profil.png
    - assets/QD1.png
    - assets/QD2.png
    - assets/QD3.png
    - assets/QD4.png

